INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Google", "Search engine", 10000, "2020-04-15", "2022-04-15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mad Dawg Technologies", "Tech support company", 3000, "2020-01-01", "2040-03-24");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Blue Man Group", "Performance artists", 5000, "2021-04-30", "2025-04-30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("J", "Detectives", 200, "2025-01-01", "2025-01-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Paddy's Pub", "Bar", 5, "2005-10-24", "2019-10-10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Krusty Krab", "Restaurant", 10, "1999-05-25", "1999-05-26");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("DGFH", "Medical non-profit", 3000, "2021-03-01", "2031-03-02");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("S", "Restaurant", 1, "2019-10-10", "2019-10-10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Three Kings", "Heavy metal band", 500, "2019-12-31", "2071-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("B", "Hair stylist", 3000000, "2018-10-31", "3018-10-31");

INSERT INTO users (name, age) VALUES ("A", 50);
INSERT INTO users (name, age) VALUES ("B", 48);
INSERT INTO users (name, age) VALUES ("C", 46);
INSERT INTO users (name, age) VALUES ("D", 44);
INSERT INTO users (name, age) VALUES ("E", 42);
INSERT INTO users (name, age) VALUES ("F", 40);
INSERT INTO users (name, age) VALUES ("G", 38);
INSERT INTO users (name, age) VALUES ("H", 36);
INSERT INTO users (name, age) VALUES ("I", 36);
INSERT INTO users (name, age) VALUES ("J", 34);
INSERT INTO users (name, age) VALUES ("K", 32);
INSERT INTO users (name, age) VALUES ("L", 30);
INSERT INTO users (name, age) VALUES ("M", 28);
INSERT INTO users (name, age) VALUES ("N", 26);
INSERT INTO users (name, age) VALUES ("O", 24);
INSERT INTO users (name, age) VALUES ("P", 22);
INSERT INTO users (name, age) VALUES ("Q", 20);
INSERT INTO users (name, age) VALUES ("R", 18);
INSERT INTO users (name, age) VALUES ("S", 16);
INSERT INTO users (name, age) VALUES ("TUVWXYZ", 14);

INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 18, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000000, 9, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 18, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000000, 9, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 18, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000000, 9, 10);
